import { Clock, Gauge, ListChecks, Sparkles } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"
import type { Summary } from "@/api/types"
import { Button } from "@/components/ui/button"

export function SummaryCard({
  summary,
  loading = false,
  onRegenerate,
}: {
  summary: Summary | null
  loading?: boolean
  onRegenerate?: () => void
}) {
  if (loading) {
    return <Card className="card-glow p-4 text-muted-warm">Loading summary…</Card>
  }
  if (summary === null) {
    return (
      <Card className="card-glow p-4">
        <p className="text-muted-warm">Summary is not available yet.</p>
        {onRegenerate ? <Button onClick={onRegenerate}>Generate summary</Button> : null}
      </Card>
    )
  }
  const stats = [
    { icon: Clock, value: `${summary.readTimeMin} min`, label: "Read time" },
    { icon: ListChecks, value: String(summary.keyPoints), label: "Key points" },
    { icon: Gauge, value: `${summary.confidence}%`, label: "Confidence" },
  ]
  return (
    <Card className="card-glow flex h-full flex-col gap-3 rounded-2xl border-warm/60 bg-card p-4">
      <div className="flex items-center justify-between gap-2">
        <h2 className="flex items-center gap-1.5 text-base font-semibold text-gold">
          AI Summary <Sparkles className="size-4" />
        </h2>
        <Badge variant="outline" className="border-copper-500/50 text-[10px] text-copper-300">
          Generated by {summary.generatedBy}
        </Badge>
      </div>
      <p className="text-sm leading-relaxed text-cream/90">{summary.content}</p>
      <div className="mt-auto grid grid-cols-3 gap-2">
        {stats.map(({ icon: Icon, value, label }) => (
          <div key={label} className="flex flex-col items-center gap-0.5 rounded-xl bg-raised py-2">
            <Icon className="size-4 text-copper-300" />
            <span className="tnum text-sm font-semibold">{value}</span>
            <span className="text-[10px] text-muted-warm">{label}</span>
          </div>
        ))}
      </div>
    </Card>
  )
}
