import { render, screen } from "@testing-library/react"
import { SummaryCard } from "../components/dashboard/SummaryCard"
import { mockDashboard } from "../data/mock"

describe("SummaryCard", () => {
  it("renders summary content and stats", () => {
    render(<SummaryCard summary={mockDashboard.summary} />)
    expect(screen.getByText(/AI Summary/)).toBeInTheDocument()
    expect(screen.getByText("Generated by VIDA")).toBeInTheDocument()
    expect(screen.getByText(/In this episode, the hosts explore/)).toBeInTheDocument()
    expect(screen.getByText("6 min")).toBeInTheDocument()
    expect(screen.getByText("8")).toBeInTheDocument()
    expect(screen.getByText("92%")).toBeInTheDocument()
    expect(screen.getByText("Read time")).toBeInTheDocument()
    expect(screen.getByText("Key points")).toBeInTheDocument()
    expect(screen.getByText("Confidence")).toBeInTheDocument()
  })
})
